### ISSUE TITLE
useragent in checkver should be used duing autoupdate

### ISSUE THREAD

**Issue by se35710** [ScoopInstaller/Scoop#4062]
When providing `useragent` in `checkver`, that useragent is not used during autoupdate, nor for hash extraction, etc.

**Comment by rashil2000** [comment]
Fixed

**Comment by vmvmpvm** [comment]
It is still not used with autoupdate, is that something you can fix as well?

**Comment by rashil2000** [comment]
Can you provide an example?

**Comment by vmvmpvm** [comment]
I was able to fix this issue for myself, and created this pull request.

are you able to review and approve it?

**Comment by rashil2000** [comment]
It will get reviewed

**Comment by rashil2000** [comment]
_From @antonoks in #5586:_

> ## Feature Request
> Add a global "**useragent**" key, which, if defined, overwrites what
> 
> https://github.com/ScoopInstaller/Scoop/blob/f93028001fbe5c78cc41f59e3814d2ac8e595724/lib/core.ps1#L26
> 
> returns
> #### Is your feature request related to a problem? Please describe.
> Some websites seem to ban"scoop". One of them is "_filezilla-project.org_". Sometimes manifests work around this ban and refer to other websites, see also the filezilla manifest. Seems like to address this kind of issue, "**checkver**" introduces the "**useragent**" key [here ](https://github.com/ScoopInstaller/Scoop/commit/8feb3867a74ea0340585e3e695934d96cf483a05). So now one can check if a new version is available based on "scoop banning sites", but still cannot "**autoupdate**" such manifests.
> 
> #### Describe the solution you'd like
> I'd like to see an "**useragent**" root key in the manifests, which, if defined, overwrites all respective user agents everywhere in the scoop tools and manifests.
> 
> #### Describe alternatives you've considered
> I thought about extending "**autosupport**" in the same way as commit [8feb386 ](https://github.com/ScoopInstaller/Scoop/commit/8feb3867a74ea0340585e3e695934d96cf483a05) extended "**checkver**", but then again I'm convinced a general "**useragend**" key would be the better solution.
